include $(CONTIKI_CPU)/Makefile.gecko_sdk

DEVICE_FAMILY := EFR32ZG23
DEVICE_SERIES := 2
RAIL_CPU := efr32xg23
RAIL_FAMILY := efr32xg2x
CUSTOM_PHY := rail_config

CFLAGS += -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse
CFLAGS += -DCUSTOM_PHY -DRAIL_SUBGHZ
CFLAGS += -DIEEE802154_CONF_DEFAULT_CHANNEL=2 -DSL_RAIL_LIB_MULITPROTOCOL_SUPPORT=0

ifdef DEBUG
    SANITIZE_FLAGS=-fstack-protector-all -fsanitize=pointer-overflow -fsanitize=null -fsanitize=builtin -fsanitize-undefined-trap-on-error
    CFLAGS += -g -gdwarf-2
    CFLAGS += -DINTERNAL -D__FILENAME__=__FILE__
else
    CFLAGS += -Os
endif

CFLAGS+=${SANTIZE_FLAGS}

LDFLAGS += -g -gdwarf-2 -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse ${SANTIZE_FLAGS}

include $(CONTIKI_CPU)/Makefile.gecko2

include $(CONTIKI)/$(CONTIKI_NG_CM33_DIR)/Makefile.cm33

include $(CONTIKI_CPU)/Makefile.commander

