include $(CONTIKI_CPU)/Makefile.gecko_sdk

DEVICE_FAMILY := EFR32ZG23
DEVICE_SERIES := 2
RAIL_CPU := efr32xg23
RAIL_FAMILY := efr32xg2x
CUSTOM_PHY := rail_config

CFLAGS += -g -gdwarf-2 -mfpu=fpv5-sp-d16  -mfloat-abi=hard -mcmse -DCUSTOM_PHY -DRAIL_SUBGHZ -DIEEE802154_CONF_DEFAULT_CHANNEL=12 -DSL_RAIL_LIB_MULITPROTOCOL_SUPPORT=0

LDFLAGS += -g -gdwarf-2 -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse

include $(CONTIKI_CPU)/Makefile.gecko2

include $(CONTIKI)/$(CONTIKI_NG_CM33_DIR)/Makefile.cm33

include $(CONTIKI_CPU)/Makefile.commander
