### Will allow the inclusion of the correct OPN makefile
DEVICE_OPN = efr32zg23b020f512im48

BOARD_SOURCEFILES += board-leds.c
BOARD_SOURCEFILES += board-buttons.c
BOARD_SOURCEFILES += sl_board_default_init.c

CFLAGS += -DBOARD_CONF_PATH=\"sgdvt-conf.h\"

CONTIKI_TARGET_DIRS += sgdvt
CONTIKI_TARGET_DIRS += sgdvt/config
